### ISSUE TITLE
[Vanilla Bug] Units attack tunnel surface when tracking targets in tunnels

### ISSUE THREAD

**Issue by Crimsonum** [Vinifera-Developers/Vinifera#784]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, debug and exception logs, etc)*.

### Description

When pursuing an enemy ground unit that enters a tunnel, if the target remains in range, the attacker will fire at the position of the target in the tunnel, hitting the surface above the tunnel. Not only does this look silly, it can cause the attackers to hit themselves or nearby friendly objects.

### Steps To Reproduce

1. Order a unit to go into a tunnel
2. Order another unit, preferably one with sufficient range, to attack it.
3. Observe how the attacker will fire at the surface above the tunnel when tracking the target.

### Expected Behaviour

The attacker should follow the target into the tunnel, or track it as usual but not fire as long as the target is in the tunnel.

### Actual Behaviour

The attacker will fire at the target's position as long as it's in range.

### Additional Context

![Example](https://user-images.githubusercontent.com/17765965/165927832-55496ae9-2546-4d06-8a6d-ee50f311afac.gif)
